// Code generated by protoc-gen-go. DO NOT EDIT.

package handlers

// TypeName returns the registered type name for the generated descriptor.
func TypeName() string {
	return "example.ProjectDescriptor"
}

// Version returns the generated schema version.
func Version() string {
	return "v1"
}
