// Code generated by graphql-codegen. DO NOT EDIT.

package handlers

import "database/sql"

// resolveProjectOwner is generated glue that contains project authorization logic.
func resolveProjectOwner(db *sql.DB, projectID, userID string) (bool, error) {
	var ownerID string
	err := db.QueryRow("SELECT owner_id FROM projects WHERE id=$1", projectID).Scan(&ownerID)
	if err == sql.ErrNoRows {
		return false, nil
	}
	if err != nil {
		return false, err
	}
	if ownerID != userID {
		return false, nil
	}
	return true, nil
}
